In [18]:
import pandas as pd 

customer_df = pd.read_csv("customer_value_analysis.csv")
customer_df.head()
customer_df.shape
customer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9134 entries, 0 to 9133
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Customer                       9134 non-null   object
 1   State                          9134 non-null   object
 2   Customer Lifetime Value        9134 non-null   float64
 3   Response                       9134 non-null   object
 4   Coverage                       9134 non-null   object
 5   Education                      9134 non-null   object
 6   Effective To Date              9134 non-null   object
 7   EmploymentStatus               9134 non-null   object
 8   Gender                         9134 non-null   object
 9   Income                         9134 non-null   int64
 10  Location Code                  9134 non-null   object
 11  Marital Status                 9134 non-null   object
 12  Monthly Premium Auto           9134 non-null   int64
 13  Months Since Last Claim        9134 non-null   int64
 14  Months Since Policy Inception  9134 non-null   int64
 15  Number of Open Complaints      9134 non-null   int64
 16  Number of Policies             9134 non-null   int64
 17  Policy Type                    9134 non-null   object
 18  Policy                         9134 non-null   object
 19  Renew Offer Type               9134 non-null   object
 20  Sales Channel                  9134 non-null   object
 21  Total Claim Amount             9134 non-null   float64
 22  Vehicle Class                  9134 non-null   object
 23  Vehicle Size                   9134 non-null   object
dtypes: float64(2), int64(6), object(16)
memory usage: 1.7+ MB

In [19]:
column_mapping = {col: col.lower().replace(' ', '_') for col in customer_df.columns}
customer_df.rename(columns=column_mapping, inplace=True)
customer_df.head()

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,...,months_since_policy_inception,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size
0,BU79786,Washington,2763.519279,No,Basic,Bachelor,2/24/11,Employed,F,56274,...,5,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
1,QZ44356,Arizona,6979.535903,No,Extended,Bachelor,1/31/11,Unemployed,F,0,...,42,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
2,AI49188,Nevada,12887.431650,No,Premium,Bachelor,2/19/11,Employed,F,48767,...,38,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
3,WW63253,California,7645.861827,No,Basic,Bachelor,1/20/11,Unemployed,M,0,...,65,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
4,HB64268,Washington,2813.692575,No,Basic,Bachelor,2/3/11,Employed,M,43836,...,44,0,1,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize

In [20]:
customer_df['effective_to_date'] = pd.to_datetime(customer_df['effective_to_date'])

In [21]:
nan_count = customer_df.isna().sum()
print(nan_count)

customer                         0
state                            0
customer_lifetime_value          0
response                         0
coverage                         0
education                        0
effective_to_date                0
employmentstatus                 0
gender                           0
income                           0
location_code                    0
marital_status                   0
monthly_premium_auto             0
months_since_last_claim          0
months_since_policy_inception    0
number_of_open_complaints        0
number_of_policies               0
policy_type                      0
policy                           0
renew_offer_type                 0
sales_channel                    0
total_claim_amount               0
vehicle_class                    0
vehicle_size                     0
dtype: int64

In [32]:
customer_df.drop('customer', axis=1)

def return_two_df(df):
    # Identify numerical columns
    num_df = df.select_dtypes(include=['int', 'float'])

    # Identify categorical columns
    cat_df = df.select_dtypes(include=['object'])
    
    return num_df, cat_df

num_df, cat_df = return_two_df(customer_df)

In [36]:
correlation_matrix = num_df.corr()
print(correlation_matrix)

                               customer_lifetime_value    income  \
customer_lifetime_value                       1.000000  0.024366
income                                        0.024366  1.000000
monthly_premium_auto                          0.396262 -0.016665
months_since_last_claim                       0.011517 -0.026715
months_since_policy_inception                 0.009418 -0.000875
number_of_open_complaints                    -0.036343  0.006408
number_of_policies                            0.021955 -0.008656
total_claim_amount                            0.226451 -0.355254

                               monthly_premium_auto  months_since_last_claim  \
customer_lifetime_value                    0.396262                 0.011517
income                                    -0.016665                -0.026715
monthly_premium_auto                       1.000000                 0.005026
months_since_last_claim                    0.005026                 1.000000
months_since_policy_inception              0.020257                -0.042959
number_of_open_complaints                 -0.013122                 0.005354
number_of_policies                        -0.011233                 0.009136
total_claim_amount                         0.632017                 0.007563

                               months_since_policy_inception  \
customer_lifetime_value                             0.009418
income                                             -0.000875
monthly_premium_auto                                0.020257
months_since_last_claim                            -0.042959
months_since_policy_inception                       1.000000
number_of_open_complaints                          -0.001158
number_of_policies                                 -0.013333
total_claim_amount                                  0.003335

                               number_of_open_complaints  number_of_policies  \
customer_lifetime_value                        -0.036343            0.021955
income                                          0.006408           -0.008656
monthly_premium_auto                           -0.013122           -0.011233
months_since_last_claim                         0.005354            0.009136
months_since_policy_inception                  -0.001158           -0.013333
number_of_open_complaints                       1.000000            0.001498
number_of_policies                              0.001498            1.000000
total_claim_amount                             -0.014241           -0.002354

                               total_claim_amount
customer_lifetime_value                  0.226451
income                                  -0.355254
monthly_premium_auto                     0.632017
months_since_last_claim                  0.007563
months_since_policy_inception            0.003335
number_of_open_complaints               -0.014241
number_of_policies                      -0.002354
total_claim_amount                       1.000000

In [37]:

def return_cont_discrete_df(df, threshold=36):
    continuous_columns = []
    discrete_columns = []
    
    for column in df.select_dtypes(include=['int', 'float']):
        unique_values = df[column].nunique()
        
        if unique_values <= threshold:
            discrete_columns.append(column)
        else:
            continuous_columns.append(column)
    
    continuous_df = df[continuous_columns]
    discrete_df = df[discrete_columns]
    
    return continuous_df, discrete_df

continuous_df, discrete_df = return_cont_discrete_df(customer_df)

In [47]:
def barplot_discrete_col(df):
   plt.figure(figsize=(16, 16))
   for column in df.columns:
        sns.countplot(x=column, data=df)
        plt.title(f"Bar Plot for {column}")
        plt.show()

In [48]:
def create_histogram_continuous(df):
    plt.figure(figsize=(16, 16))
    for column in df.columns:
        sns.histplot(df[column], kde=True)
        plt.title(f"Histogram for {column}")
        plt.show()

In [49]:
def create_boxplot_continuous(df):
    plt.figure(figsize=(16, 16))
    for column in df.columns:
        sns.boxplot(x=df[column])
        plt.title(f"Box Plot for {column}")
        plt.show()